name: My First GitHub Action

on:
  workflow_dispatch: # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000226@ds.study.iitm.ac.in
        run: echo "Hello, world!"
